### ISSUE TITLE
Oauth google and github 404s in deployment

### ISSUE THREAD

**Issue by StraubJones** [CollaBoard/CollaBoard#139]

**Comment by StraubJones** [comment]
The heroku deployed app is getting 404s when you try to login with google or github

**Comment by leftynaut** [comment]
Need to update callbacks. @shamsup, can we just use `/auth/google/callback` and `/auth/github/callback` like you can in Passport?

**Comment by shamsup** [comment]
It's actually because the `redirect_uri` in our github and google application settings doesn't match the heroku domain we have set up. Once we switch app names to something more permanent, then we just have to update those.

**Comment by shamsup** [comment]
Created production apps in google and github and configured the heroku env variables to use those instead of the development apps
